version: "3.2"
services:
  elastic-search:
    container_name: elastic-search
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.1
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - "xpack.security.enrollment.enabled=false"
      - "xpack.security.http.ssl.enabled=false"
      - "xpack.security.transport.ssl.enabled=false"
      - ELASTIC_PASSWORD=1234
    networks:
      - elastic-network
    ports:
      - "9300:9300"
      - "9200:9200"
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.10.1
    networks:
      - elastic-network
    ports:
      - "5601:5601"
networks:
  elastic-network:
    driver: bridge